version: '3.8'

services:
  attack-manager:
    build:
      context: .
      dockerfile: Dockerfile
    image: gosynflood-manager:latest
    container_name: gosynflood-manager
    ports:
      - "31457:31457"
    volumes:
      - attack_data:/app/data
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN:-change-me-to-secure-token}
    restart: unless-stopped

volumes:
  attack_data:
    name: gosynflood_attack_data 