services:
  attack-manager:
    container_name: gosynflood-manager
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    image: gosynflood-manager:local
    ports:
      - "31457:31457"
    volumes:
      - attack_data:/app/data
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN:-change-me-to-secure-token}
    restart: unless-stopped

volumes:
  attack_data:
    name: gosynflood_attack_data 